CREATE TABLE giftaid.CUSTOMER 
(
  SHEETNO VARCHAR(16) NOT NULL 
, SHOP VARCHAR(24) NOT NULL 
, BARCODE VARCHAR(24) 
, TITLE VARCHAR(6) 
, FORENAME VARCHAR(48) 
, SURNAME VARCHAR(16) 
, ADDRESS VARCHAR(128) 
, TOWN VARCHAR(32) 
, POSTCODE VARCHAR(12) 
, TELEPHONE VARCHAR(16) 
, EMAIL VARCHAR(64) 
, POST_ME VARCHAR(8) 
, TELE_ME VARCHAR(20) 
, EMAIL_ME VARCHAR(20) 
, CDATE VARCHAR(20) DEFAULT (GETDATE())
, CONSTRAINT CUSTOMER_PK PRIMARY KEY (SHEETNO , SHOP )
)
  
ALTER TABLE CUSTOMER  
MODIFY (SHEETNO NOT NULL);

ALTER TABLE CUSTOMER  
MODIFY (SHOP NOT NULL);
