CREATE TABLE giftaid.CUSTOMER 
(
  SHEETNO VARCHAR2(16) NOT NULL 
, SHOP VARCHAR2(24) NOT NULL 
, BARCODE VARCHAR2(24) 
, TITLE VARCHAR2(6) 
, FORENAME VARCHAR2(48) 
, SURNAME VARCHAR2(16) 
, ADDRESS VARCHAR2(128) 
, TOWN VARCHAR2(32) 
, POSTCODE VARCHAR2(12) 
, TELEPHONE VARCHAR2(16) 
, EMAIL VARCHAR2(64) 
, POST_ME VARCHAR2(8) 
, TELE_ME VARCHAR2(20) 
, EMAIL_ME VARCHAR2(20) 
, CDATE VARCHAR2(20) DEFAULT (GETDATE())
, CONSTRAINT CUSTOMER_PK PRIMARY KEY (SHEETNO , SHOP )
)
  
ALTER TABLE CUSTOMER  
MODIFY (SHEETNO NOT NULL);

ALTER TABLE CUSTOMER  
MODIFY (SHOP NOT NULL);
